backend/urls.py
from django.conf.urls import include, url
from views import LoginView, SettingView, Register,CateSetting,AddCate,IndexView,Article,AddArticle,AddArticleDetail,\
UploadImg,CarouselSetting,AddCarouselItem,ModifyCarouselItem,DeleteCarouselItem,DeleteArticle,ConfirmArticle,AddArticleImg,\
ModifyArticleImg,DeleteArticleImg,YingShiNanGuo,AddMediaArticle,DeleteMediaArticle,ConfirmMediaArticle,AuthGroupSetting,\
AddGroup,OperationLog,DeleteGroup,GroupSetting,CitySetting,AddCity,AddArea,DeleteArea,DeleteCity,TopicSetting,AddTopicArticle,\
DeleteTopicArticle, AddTopicCover
from django.contrib.auth.models import User


urlpatterns = [
    url(r'^login/$',LoginView.as_view(),name="login"),
    url(r'^setting/$',SettingView.as_view(),name="setting"),
    url(r'^register/$',Register.as_view(),name="register"),
    url(r'^cate_setting/$',CateSetting.as_view(),name="cate_setting"),
    url(r'^add_cate/$',AddCate.as_view(),name="add_cate"),
    url(r'^index/$',IndexView.as_view(),name="index"),
    url(r'^article/$',Article.as_view(),name="article"),
    url(r'^add_article/$',AddArticle.as_view(),name="add_article"),
    url(r'^add_article_detail/(?P<article_id>\w+)/$',AddArticleDetail.as_view(),name="add_article_detail"),
    url(r'^upload_img/$',UploadImg.as_view(),name="upload_img"),
    url(r'^carousel_setting/$',CarouselSetting.as_view(),name="carousel_setting"),
    url(r'^add_carousel_item/$',AddCarouselItem.as_view(),name="add_carousel_item"),
    url(r'^modify_carousel_item/$',ModifyCarouselItem.as_view(),name="modify_carousel_item"),
    url(r'^delete_carousel_item/$',DeleteCarouselItem.as_view(),name="delete_carousel_item"),
    url(r'^delete_article/$',DeleteArticle.as_view(),name="delete_article"),
    url(r'^confirm_article/$',ConfirmArticle.as_view(),name="confirm_article"),
    url(r'^add_article_img/$',AddArticleImg.as_view(),name="add_article_img"),
    url(r'^modify_article_img/$',ModifyArticleImg.as_view(),name="modify_article_img"),
    url(r'^delete_article_img/$',DeleteArticleImg.as_view(),name="delete_article_img"),
    url(r'^yingshinanguo/$',YingShiNanGuo.as_view(),name="yingshinanguo"),
    url(r'^add_media_article/$',AddMediaArticle.as_view(),name="add_media_article"),
    url(r'^delete_media_article/$',DeleteMediaArticle.as_view(),name="delete_media_article"),
    url(r'^confirm_media_article/$',ConfirmMediaArticle.as_view(),name="confirm_media_article"),
    url(r'^auth_group/$',AuthGroupSetting.as_view(),name="auth_group"),
    url(r'^add_group/$',AddGroup.as_view(),name="add_group"),
    url(r'^operation_log/$',OperationLog.as_view(),name="operation_log"),
    url(r'^delete_group/$',DeleteGroup.as_view(),name="delete_group"),
    url(r'^group_setting/$',GroupSetting.as_view(),name="group_setting"),
    url(r'^city_setting/$',CitySetting.as_view(),name="city_setting"),
    url(r'^add_city/$',AddCity.as_view(),name="add_city"),
    url(r'^add_area/$',AddArea.as_view(),name="add_area"),
    url(r'^delete_area/$',DeleteArea.as_view(),name="delete_area"),
    url(r'^delete_city/$',DeleteCity.as_view(),name="delete_city"),
    url(r'^topic_setting/$',TopicSetting.as_view(),name="topic_setting"),
    url(r'^add_topic_article/$',AddTopicArticle.as_view(),name="add_topic_article"),
    url(r'^delete_topic_article/$',DeleteTopicArticle.as_view(),name="delete_topic_article"),
    url(r'add_topic_cover/(?P<topic_id>\w+)/$',AddTopicCover.as_view(),name="add_topic_cover"),
]

pc_front/urls.py
from django.conf.urls import include, url
from views import IndexList,BeautifulGx,DCMZ,BGDD,RWYS,YDYL,WHJS,ZhiGuanTianXia,ZGZX,QYLY,LTGY,\
SYTD,JXTJ,XunChengJi,LYDL,CSWD,MFMS,SCFZ,FengShangGuangXi,FMGS,FSWH,JZNR,FSNS,LXSH, PinZhuoRenSheng,\
HuiZhanFuWu,HZCH,HYFW,YingShiNanGuo,XWFM,XKC,BHM,PZDT,PZWH,PZPP,PZPJ,ShuiMoDanQing,MRT,SMYX,SMWJ,ArticleDetail,\
MediaDetail,QYDH,RWDL,TSSC,HZZX, TopicArticleList, AreaArticleList,SMYL
from models import ImgArticle,Cate

urlpatterns = [
    url(r'^index/$',IndexList.as_view(),name="index"),
    url(r'^beautiful_gx/$',BeautifulGx.as_view(),name="beautiful_gx"),
    url(r'^dcmz/$',DCMZ.as_view(),name="dcmz"),
    url(r'^bgdd/$',BGDD.as_view(),name="bgdd"),
    url(r'^rwys/$',RWYS.as_view(),name="rwys"),
    url(r'^ydyl/$',YDYL.as_view(),name="ydyl"),
    url(r'^whjs/$',WHJS.as_view(),name="whjs"),
    url(r'^zhiguantianxia/$',ZhiGuanTianXia.as_view(),name="zhiguantianxia"),
    url(r'^zhiguanzixun/$',ZGZX.as_view(),name="zhiguanzixun"),
    url(r'^quanyulvyou/$',QYLY.as_view(),name="quanyulvyou"),
    url(r'^lvtuguangying/$',LTGY.as_view(),name="lvtuguangying"),
    url(r'^shiyoutaidu/$',SYTD.as_view(),name="shiyoutaidu"),
    url(r'^jingxuantuijian/$',JXTJ.as_view(),name="jingxuantuijian"),
    url(r'^xunchengji/$',XunChengJi.as_view(),name="xunchengji"),
    url(r'^lvyoudili/$',LYDL.as_view(),name="lvyoudili"),
    url(r'^chengshiweidao/$',CSWD.as_view(),name="chengshiweidao"),
    url(r'^minfengminsu/$',MFMS.as_view(),name="minfengminsu"),
    url(r'^shengchanfazhan/$',SCFZ.as_view(),name="shengchanfazhan"),
    url(r'^fengshangguangxi/$',FengShangGuangXi.as_view(),name="fengshangguangxi"),
    url(r'^fengmiangushi/$',FMGS.as_view(),name="fengmiangushi"),
    url(r'^fengshangwenhua/$',FSWH.as_view(),name="fengshangwenhua"),
    url(r'^jingzhinvren/$',JZNR.as_view(),name="jingzhinvren"),
    url(r'^fengshangnanshi/$',FSNS.as_view(),name="fengshangnanshi"),
    url(r'^lexiangshenghuo/$',LXSH.as_view(),name="lexiangshenghuo"),
    url(r'^pinzhuorensheng/$',PinZhuoRenSheng.as_view(),name="pinzhuorensheng"),
    url(r'^huizhanfuwu/$',HuiZhanFuWu.as_view(),name="huizhanfuwu"),
    url(r'^huizhancehua/$',HZCH.as_view(),name="huizhancehua"),
    url(r'^huiyifuwu/$',HYFW.as_view(),name="huiyifuwu"),
    url(r'^yingshinanguo/$',YingShiNanGuo.as_view(),name="yingshinanguo"),
    url(r'^xinwangfm/$',XWFM.as_view(),name="xinwangfm"),
    url(r'^xiaokachuang/$',XKC.as_view(),name="xiaokachuang"),
    url(r'^bahaomi/$',BHM.as_view(),name="bahaomi"),
    url(r'^pinzhuodongtai/$',PZDT.as_view(),name="pinzhuodongtai"),
    url(r'^pinzhuowenhua/$',PZWH.as_view(),name="pinzhuowenhua"),
    url(r'^pinzhuopinpai/$',PZPP.as_view(),name="pinzhuopinpai"),
    url(r'^pinzhuopinjian/$',PZPJ.as_view(),name="pinzhuopinjian"),
    url(r'^shuimodanqing/$',ShuiMoDanQing.as_view(),name="shuimodanqing"),
    url(r'^mingrentang/$',MRT.as_view(),name="mingrentang"),
    url(r'^shuimoyixun/$',SMYX.as_view(),name="shuimoyixun"),
    url(r'^shuimowujie/$',SMWJ.as_view(),name="shuimowujie"),
    url(r'^article_detail/(?P<article_id>\w+)/$',ArticleDetail.as_view(),name="article_detail"),
    url(r'^media_detail/(?P<article_id>\w+)/$',MediaDetail.as_view(),name="media_detail"),
    url(r'^quyudaohang/$',QYDH.as_view(),name="quyudaohang"),
    url(r'^renwendili/$',RWDL.as_view(),name="renwendili"),
    url(r'^teseshengchan/$',TSSC.as_view(),name="teseshengchan"),
    url(r'^huizhanzixun/$',HZZX.as_view(),name="huizhanzixun"),
    url(r'^topic_article_list/$',TopicArticleList.as_view(),name="topic_article_list"),
    url(r'^area_article_list/$',AreaArticleList.as_view(),name="area_article_list"),
    url(r'^shuimoyilang/$',SMYL.as_view(),name="shuimoyilang"),
]

xzgxcms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from pc_front.views import IndexList
from django.views.static import serve

urlpatterns = [
    # Examples:
    # url(r'^$', 'xzgxcms.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^front/',include('pc_front.urls',namespace='pc_front')),
    url(r'^backend/',include('backend.urls',namespace='backend')),
    url(r'^$',IndexList.as_view(),name="index"),
    url(r'^site_media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT})
] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

backend/models.py
# -*- coding:utf-8 -*- 
from django.db import models
from pc_front.models import Cate, ImgArticle

# Create your models here.
class Carousel(models.Model):
    name = models.CharField(max_length=100,help_text="轮播名称")
    query_code = models.CharField(max_length=100,help_text="用于查询轮播")

class CarouselItem(models.Model):
    carousel = models.ForeignKey(Carousel,help_text="所属轮播",on_delete=models.CASCADE)
    img = models.ImageField(upload_to="carousel_img",help_text="轮播图片")
    title = models.CharField(max_length=200,help_text="轮播标题")
    desc = models.CharField(max_length=200,help_text="轮播简介")
    url = models.CharField(max_length=500,help_text="轮播所指向的url")

    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    class Meta:
    	permissions = (
            ('add_carousel_item',"添加轮播"),
            ('modify_carousel_item',"修改轮播"),
            ('delete_carousel_item',"删除轮播")
    		)


class OperationLog(models.Model):
	username = models.CharField(max_length=100)
	content = models.CharField(max_length=500)
	log_type = models.IntegerField(default=0,help_text="0:内容日志，1：系统日志")

	created_time = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-created_time']


class FriendLink(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=200)
    index = models.IntegerField(default=0,help_text="排序")

    class Meta:
        ordering = ['index']

class Topic(models.Model):
    name = models.CharField(max_length=20)
    cover = models.ImageField(upload_to="carousel_img",blank=True,null=True)

class TopicArticle(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    article = models.ForeignKey(ImgArticle,on_delete=models.CASCADE)

pc_front/models.py
# -*- coding:utf-8 -*- 
from django.db import models
from mptt.models import MPTTModel

# Create your models here.

class Cate(MPTTModel):
    parent = models.ForeignKey("self",blank=True,null=True,related_name="children",verbose_name="上级分类")
    name = models.CharField(max_length=200,help_text="分类名称",verbose_name="分类名称")
    cover = models.ImageField(upload_to='cate_cover',help_text="分类图片",verbose_name="分类图片")
    description = models.CharField(max_length=500,help_text="分类描述",blank=True,null=True,verbose_name="分类简介")
    query_code = models.CharField(max_length=20,help_text="用于查询分类实例",blank=True,null=True)
    description = models.CharField(max_length=500,help_text="分类简介",blank=True,null=True)
    media = models.FileField(blank=True,null=True,help_text="分类短片")
    url = models.CharField(max_length=200,help_text="分类的url",blank=True,null=True)
    is_article = models.BooleanField(default=0,help_text="分类下是否有文章，0：无，1：有")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "分类"
        ordering = ['id']

class City(models.Model):
    name = models.CharField(max_length=20)
    cover = models.ImageField(upload_to='cate_cover',blank=True,null=True)

class Area(models.Model):
    name = models.CharField(max_length=20)
    city = models.ForeignKey(City,on_delete=models.CASCADE)

class Famous(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200,blank=True,null=True)
    cover = models.ImageField(upload_to="article_img",blank=True,null=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)


class ImgArticle(models.Model):
    title = models.CharField(max_length=200,help_text="文章标题")
    cate = models.ForeignKey(Cate,help_text="所属分类",on_delete=models.CASCADE)
    cover = models.ImageField(upload_to="article_img",help_text="文章封面")
    author = models.CharField(max_length=50,help_text="文章作者",blank=True,null=True)
    description = models.CharField(max_length=500,help_text="文章简介",blank=True,null=True)
    content = models.TextField()
    label = models.CharField(max_length=100,blank=True,null=True,help_text="文章标签")
    status = models.BooleanField(default=0,help_text="是否审核，0：未审核，1：已审核")
    display_mode = models.IntegerField(default=0,help_text="文章显示模式，0：标准模式，1：多图模式")
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    area = models.ForeignKey(Area,blank=True,null=True,on_delete=models.SET_NULL)
    famous = models.ForeignKey(Famous,blank=True,null=True,on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "图片文章"
        ordering = ['-update_time']

        permissions = (
            ("add_img_article","添加图片文章"),
            ("modify_img_article","修改图片文章"),
            ("delete_img_article","删除图片文章"),
            ("confirm_img_article","审核图片文章")
            )

class Images(models.Model):
    article = models.ForeignKey(ImgArticle,help_text="所属文章",on_delete=models.CASCADE)
    img = models.ImageField(upload_to="article_img")
    title = models.CharField(max_length=200,blank=True,null=True,help_text="图片标题")
    description = models.CharField(max_length=500,null=True,blank=True,help_text="图片简介")



class MediaArticle(models.Model):
    title = models.CharField(max_length=200,help_text="文章标题")
    cate = models.ForeignKey(Cate,help_text="所属分类",on_delete=models.CASCADE)
    cover = models.ImageField(upload_to="article_img",help_text="文章封面")
    author = models.CharField(max_length=50,help_text="文章作者",blank=True,null=True)
    media = models.FileField(upload_to="article_media")
    description = models.CharField(max_length=500,help_text="文章简介",blank=True,null=True)
    label = models.CharField(max_length=100,blank=True,null=True,help_text="文章标签")
    status = models.BooleanField(default=0,help_text="是否审核，0：未审核，1：已审核")
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "影视文章"
        ordering = ['-update_time']

        permissions = (
            ("add_media_article","添加视频文章"),
            ("modify_media_article","修改视频文章"),
            ("delete_media_article","删除视频文章"),
            ("confirm_media_article","审核视频文章")
            )

pc_front/templates/pc_front/smwj.html
{% extends 'pc_front/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans '无界' %}{% endblock %}
{% block content %}

{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'pc_front/css/sub_shuimodanqing.css' %}">

<div class="layui-row">
  <div class="layui-col-md8 layui-col-md-offset2">
  <div class="layui-carousel" id="carousel" >
		<div carousel-item>
			{% for item in carousel.carouselitem_set.all %}
      <div class="carousel_div" style="background-image: url('/site_media/{{item.img}}');"></div>
      {% endfor %}
		</div>
	</div>
  </div>
</div>

<div class="layui-row">
  <div class="layui-col-md8 layui-col-md-offset2">
    <ul class="shuimo_list">
      <li><a href="{% url 'pc_front:index' %}">{% trans '首页' %}</a></li>
      <li><a href="{% url 'pc_front:shuimoyilang' %}">{% trans '艺廊' %}</a></li>
      <li><a href="{% url 'pc_front:mingrentang' %}">{% trans '名人堂' %}</a></li>
      <li><a href="{% url 'pc_front:shuimoyixun' %}">{% trans '艺讯' %}</a></li>
      <li><a href="{% url 'pc_front:shuimowujie' %}">{% trans '无界' %}</a></li>
    </ul>
  </div>
</div>

<div class="layui-row mingrentang_title">
  <div class="layui-col-md3 layui-col-md-offset2">
    {% trans '无界   Unbounded' %}
  </div>
</div>

<div class="layui-row">
  <div class="layui-col-md8 layui-col-md-offset2">
    <ul class="wujie_list">
    {% for article in articles %}
      <a href="{% url 'pc_front:article_detail' article.id %}"><li>
        <div class="wujie_img" style="background-image: url('/site_media/{{article.cover}}')"></div>
        <div class="wujie_title">{{article.title}}</div>
      </li></a>
    {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}
{% endblock %}

{% block script %}
<script type="text/javascript">
  $(document).ready(function(){
    layui.use('carousel',function(){
      var carousel = layui.carousel;

      carousel.render({
        elem:"#carousel",
        width:"100%",
        height:"510px",
        arrow:"hover",
      })
    })

    layui.use('carousel',function(){
      var carousel = layui.carousel;

      carousel.render({
        elem:"#carousel2",
        width:"100%",
        height:"300px",
        arrow:"hover",
        indicator:"none",
      })
    })
  })
</script>
{% endblock %}

pc_front/templates/pc_front/xwfm.html
{% extends 'pc_front/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans '新网FM' %}{% endblock %}
{% block content %}
{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'pc_front/css/sub_yingshinanguo.css' %}">
<link rel="stylesheet" href="{% static 'pc_front/css/swiper.min.css' %}">

<div class="layui-row main_title">
	<div class="layui-col-md4 layui-col-md-offset4">
		<img src="#">
	</div>
</div>

<div class="layui-row">
	<div class="layui-col-md8 layui-col-md-offset2">
		<ul class="cate_list">
		    <li><a href="{% url 'pc_front:index' %}">{% trans '首页' %}</a></li>
			<li><a href="{% url 'pc_front:quyudaohang' %}">{% trans '区域导航' %}</a></li>
			<li><a href="{% url 'pc_front:beautiful_gx' %}">{% trans '最美广西' %}</a></li>
			<li><a href="{% url 'pc_front:zhiguantianxia' %}">{% trans '直观天下' %}</a></li>
			<li><a href="{% url 'pc_front:xunchengji' %}">{% trans '寻城记' %}</a></li>
			<li><a href="#">{% trans '水墨丹青' %}</a></li>
			<li><a href="{% url 'pc_front:fengshangguangxi' %}">{% trans '风尚广西' %}</a></li>
			<li><a href="{% url 'pc_front:yingshinanguo' %}">{% trans '影视南国' %}</a></li>
			<li><a href="{% url 'pc_front:huizhanfuwu' %}">{% trans '会展策划' %}</a></li>
			<li><a href="{% url 'pc_front:pinzhuorensheng' %}">{% trans '品酌人生' %}</a></li>
		</ul>
	</div>
</div>

<div class="layui-row">
	<div class="layui-col-md8 layui-col-md-offset2">
		<img src="#" class="xinwang_banner" />
	</div>
</div>

<div class="layui-row">
	<div class="layui-col-md6 layui-col-md-offset2">
		<div class="xinwang_title"><span class="xinwang_sub_title1">{% trans '新网FM' %}</span><span class="xinwang_sub_title2">{% trans '推荐视频' %}</span></div>
	</div>

	<div class="layui-col-md2">
		<div class="xinwang_title"><span class="xinwang_sub_title1">{% trans '热点排行' %}</span></div>
	</div>
</div>

<div class="layui-row xinwang_main_row">
	<div class="layui-col-md8 layui-col-md-offset2">
		<div class="layui-row">
			<div class="layui-col-md6" style="height: 425px;">
			<div class="swiper-container gallery-top">
    <div class="swiper-wrapper">
          {% for item in carousel.carouselitem_set.all %}
      <div class="swiper-slide" style="background-image:url(/site_media/{{item.img}});position: relative;">
      <a href="{{item.url}}">
        <div style="position: absolute;bottom: 50px;left: 30px;">
          <div style="color: white;text-align: center;font-weight: bold;font-size: 30px;">{{item.title}}</div>
          <div style="color: white;text-align: center;font-weight: bold;font-size: 18px;">{{item.desc}}</div>
        </div>
      </a>
      </div>
    {% endfor %}
    </div>
    <!-- Add Arrows -->
    <div class="swiper-button-next swiper-button-white"></div>
    <div class="swiper-button-prev swiper-button-white"></div>
  </div>
  <div class="swiper-container gallery-thumbs">
    <div class="swiper-wrapper">
    {% for item in carousel.carouselitem_set.all %}
      <div class="swiper-slide" style="background-image:url(/site_media/{{item.img}})"></div>
    {% endfor %}
    </div>
  </div>
			<!--
				<div class="layui-carousel" id="carousel" >
		          <div carousel-item>
			        <div class="carousel_div">
			          <div class="carousel_title">
			            <div>我是标题标题标题<br />我是导语</div>
			            </div>
			          </div>
			          <div class="carousel_div">
			            <div class="carousel_title">
			              <div>我是标题标题标题<br />我是导语</div>
			              </div>
			            </div>
			          <div class="carousel_div">
			            <div class="carousel_title">
			              <div>我是标题标题标题<br />我是导语</div>
			              </div></div>
			          <div class="carousel_div">
			            <div class="carousel_title">
			              <div>我是标题标题标题<br />我是导语</div>
			            </div></div>
		              </div>
	            </div>
	          -->
			</div>
			<div class="layui-col-md3">
				<ul class="xinwang_carousel_left_ul">
				{% for article in main_article %}
				  <a href="{% url 'pc_front:media_detail' article.id %}">
					<li>
					  <div style="background-image: url('/site_media/{{article.cover}}');"></div>
					</li>
				  </a>
				{% endfor %}
				</ul>
			</div>
		</div>
        
        <div>
		</div>

	</div>

	<div class="xinwang_right" ">
			<ul class="xinwang_carousel_right_ul">
			   {% for rank in hot_rank %}
				<a href="{% url 'pc_front:media_detail' rank.id %}"><li><div style="background-image: url('/site_media/{{rank.cover}}');"></div></li></a>
			   {% endfor %}
			</ul>
</div>
</div>

<div class="layui-row xinwang_second_row">
	<div class="layui-col-md6 layui-col-md-offset2">
		<ul class="xinwang_second_ul">
		{% for article in articles %}
			<a href="{% url 'pc_front:media_detail' article.id %}"><li><img src="/site_media/{{article.cover}}" /><div class="xinwang_second_title">{{article.title}}</div><div class="xinwang_second_desc">{{article.description}}</div></li></a>
		{% endfor %}
		</ul>
	</div>
</div>


{% if is_paginated %}
<div class="layui-row"> 
<div class="layui-col-md12" style="text-align: center;"> 
    <div class="pagination">  
        <span class="page-links">  
            {% if page_obj.has_previous %}  
                <a class="layui-btn layui-btn-primary" href="/pc_front/xinwangfm?page={{ page_obj.previous_page_number }}">上一页</a>  
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
            {% if i == page_obj.number %}
                <span style="padding: 25px;vertical-align: middle;">{{i}}</span>
            {% else %}
                <a class="layui-btn layui-btn-primary" href="/pc_front/xinwangfm?page={{i}}">{{i}}</a>
            {% endif %}
            
            {% endfor %}
            {% if page_obj.has_next %}  
                <a class="layui-btn layui-btn-primary" href="/pc_front/xinwangfm?page={{ page_obj.next_page_number }}">下一页</a>  
            {% endif %}  
           <!-- <span class="page-current">  
                第{{ page_obj.number }}页 ，共{{ page_obj.paginator.num_pages }}页。  
            </span>  -->
        </span>  
    </div>  
</div>
</div>
{%endif%} 



{% endblock %}
{% endblock %}

{% block script %}
<style type="text/css">
.swiper-container {
      width: 100%;
      height: 300px;
      margin-left: auto;
      margin-right: auto;
    }
    .swiper-slide {
      background-size: cover;
      background-position: center;
    }
    .gallery-top {
      height: 80%;
      width: 100%;
    }
    .gallery-thumbs {
      height: 20%;
      box-sizing: border-box;
      padding: 10px 0;
    }
    .gallery-thumbs .swiper-slide {
      height: 100%;
      opacity: 0.4;
    }
    .gallery-thumbs .swiper-slide-active {
      opacity: 1;
    }
</style>
<script src="{% static 'pc_front/js/swiper.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
		layui.use('carousel',function(){
			var carousel = layui.carousel;

			carousel.render({
				elem:"#carousel",
				width:"100%",
				height:"425px",
				arrow:"hover",
				indicator:"none"
			})
		})


	var galleryTop = new Swiper('.gallery-top', {
      spaceBetween: 10,
      loop:true,
      loopedSlides: 5, //looped slides should be the same
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
    var galleryThumbs = new Swiper('.gallery-thumbs', {
      spaceBetween: 10,
      slidesPerView: 4,
      touchRatio: 0.2,
      loop: true,
      loopedSlides: 5, //looped slides should be the same
      slideToClickedSlide: true,
    });
    galleryTop.controller.control = galleryThumbs;
    galleryThumbs.controller.control = galleryTop;
    
	})
</script>
{% endblock %}