backend/urls.py
from django.conf.urls import include, url
from views import LoginView, SettingView, Register,CateSetting,AddCate,IndexView,Article,AddArticle,AddArticleDetail,\
UploadImg,CarouselSetting,AddCarouselItem,ModifyCarouselItem,DeleteCarouselItem,DeleteArticle,ConfirmArticle,AddArticleImg,\
ModifyArticleImg,DeleteArticleImg,YingShiNanGuo,AddMediaArticle,DeleteMediaArticle,ConfirmMediaArticle,AuthGroupSetting,\
AddGroup,OperationLog,DeleteGroup,GroupSetting,CitySetting,AddCity,AddArea,DeleteArea,DeleteCity,TopicSetting,AddTopicArticle,\
DeleteTopicArticle, AddTopicCover
from django.contrib.auth.models import User


urlpatterns = [
    url(r'^login/$',LoginView.as_view(),name="login"),
    url(r'^setting/$',SettingView.as_view(),name="setting"),
    url(r'^register/$',Register.as_view(),name="register"),
    url(r'^cate_setting/$',CateSetting.as_view(),name="cate_setting"),
    url(r'^add_cate/$',AddCate.as_view(),name="add_cate"),
    url(r'^index/$',IndexView.as_view(),name="index"),
    url(r'^article/$',Article.as_view(),name="article"),
    url(r'^add_article/$',AddArticle.as_view(),name="add_article"),
    url(r'^add_article_detail/(?P<article_id>\w+)/$',AddArticleDetail.as_view(),name="add_article_detail"),
    url(r'^upload_img/$',UploadImg.as_view(),name="upload_img"),
    url(r'^carousel_setting/$',CarouselSetting.as_view(),name="carousel_setting"),
    url(r'^add_carousel_item/$',AddCarouselItem.as_view(),name="add_carousel_item"),
    url(r'^modify_carousel_item/$',ModifyCarouselItem.as_view(),name="modify_carousel_item"),
    url(r'^delete_carousel_item/$',DeleteCarouselItem.as_view(),name="delete_carousel_item"),
    url(r'^delete_article/$',DeleteArticle.as_view(),name="delete_article"),
    url(r'^confirm_article/$',ConfirmArticle.as_view(),name="confirm_article"),
    url(r'^add_article_img/$',AddArticleImg.as_view(),name="add_article_img"),
    url(r'^modify_article_img/$',ModifyArticleImg.as_view(),name="modify_article_img"),
    url(r'^delete_article_img/$',DeleteArticleImg.as_view(),name="delete_article_img"),
    url(r'^yingshinanguo/$',YingShiNanGuo.as_view(),name="yingshinanguo"),
    url(r'^add_media_article/$',AddMediaArticle.as_view(),name="add_media_article"),
    url(r'^delete_media_article/$',DeleteMediaArticle.as_view(),name="delete_media_article"),
    url(r'^confirm_media_article/$',ConfirmMediaArticle.as_view(),name="confirm_media_article"),
    url(r'^auth_group/$',AuthGroupSetting.as_view(),name="auth_group"),
    url(r'^add_group/$',AddGroup.as_view(),name="add_group"),
    url(r'^operation_log/$',OperationLog.as_view(),name="operation_log"),
    url(r'^delete_group/$',DeleteGroup.as_view(),name="delete_group"),
    url(r'^group_setting/$',GroupSetting.as_view(),name="group_setting"),
    url(r'^city_setting/$',CitySetting.as_view(),name="city_setting"),
    url(r'^add_city/$',AddCity.as_view(),name="add_city"),
    url(r'^add_area/$',AddArea.as_view(),name="add_area"),
    url(r'^delete_area/$',DeleteArea.as_view(),name="delete_area"),
    url(r'^delete_city/$',DeleteCity.as_view(),name="delete_city"),
    url(r'^topic_setting/$',TopicSetting.as_view(),name="topic_setting"),
    url(r'^add_topic_article/$',AddTopicArticle.as_view(),name="add_topic_article"),
    url(r'^delete_topic_article/$',DeleteTopicArticle.as_view(),name="delete_topic_article"),
    url(r'add_topic_cover/(?P<topic_id>\w+)/$',AddTopicCover.as_view(),name="add_topic_cover"),
]

xzgxcms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from pc_front.views import IndexList
from django.views.static import serve

urlpatterns = [
    # Examples:
    # url(r'^$', 'xzgxcms.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^front/',include('pc_front.urls',namespace='pc_front')),
    url(r'^backend/',include('backend.urls',namespace='backend')),
    url(r'^$',IndexList.as_view(),name="index"),
    url(r'^site_media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT})
] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

backend/models.py
# -*- coding:utf-8 -*- 
from django.db import models
from pc_front.models import Cate, ImgArticle

# Create your models here.
class Carousel(models.Model):
    name = models.CharField(max_length=100,help_text="轮播名称")
    query_code = models.CharField(max_length=100,help_text="用于查询轮播")

class CarouselItem(models.Model):
    carousel = models.ForeignKey(Carousel,help_text="所属轮播",on_delete=models.CASCADE)
    img = models.ImageField(upload_to="carousel_img",help_text="轮播图片")
    title = models.CharField(max_length=200,help_text="轮播标题")
    desc = models.CharField(max_length=200,help_text="轮播简介")
    url = models.CharField(max_length=500,help_text="轮播所指向的url")

    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    class Meta:
    	permissions = (
            ('add_carousel_item',"添加轮播"),
            ('modify_carousel_item',"修改轮播"),
            ('delete_carousel_item',"删除轮播")
    		)


class OperationLog(models.Model):
	username = models.CharField(max_length=100)
	content = models.CharField(max_length=500)
	log_type = models.IntegerField(default=0,help_text="0:内容日志，1：系统日志")

	created_time = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-created_time']


class FriendLink(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=200)
    index = models.IntegerField(default=0,help_text="排序")

    class Meta:
        ordering = ['index']

class Topic(models.Model):
    name = models.CharField(max_length=20)
    cover = models.ImageField(upload_to="carousel_img",blank=True,null=True)

class TopicArticle(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    article = models.ForeignKey(ImgArticle,on_delete=models.CASCADE)

pc_front/models.py
# -*- coding:utf-8 -*- 
from django.db import models
from mptt.models import MPTTModel

# Create your models here.

class Cate(MPTTModel):
    parent = models.ForeignKey("self",blank=True,null=True,related_name="children",verbose_name="上级分类")
    name = models.CharField(max_length=200,help_text="分类名称",verbose_name="分类名称")
    cover = models.ImageField(upload_to='cate_cover',help_text="分类图片",verbose_name="分类图片")
    description = models.CharField(max_length=500,help_text="分类描述",blank=True,null=True,verbose_name="分类简介")
    query_code = models.CharField(max_length=20,help_text="用于查询分类实例",blank=True,null=True)
    description = models.CharField(max_length=500,help_text="分类简介",blank=True,null=True)
    media = models.FileField(blank=True,null=True,help_text="分类短片")
    url = models.CharField(max_length=200,help_text="分类的url",blank=True,null=True)
    is_article = models.BooleanField(default=0,help_text="分类下是否有文章，0：无，1：有")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "分类"
        ordering = ['id']

class City(models.Model):
    name = models.CharField(max_length=20)
    cover = models.ImageField(upload_to='cate_cover',blank=True,null=True)

class Area(models.Model):
    name = models.CharField(max_length=20)
    city = models.ForeignKey(City,on_delete=models.CASCADE)

class Famous(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200,blank=True,null=True)
    cover = models.ImageField(upload_to="article_img",blank=True,null=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)


class ImgArticle(models.Model):
    title = models.CharField(max_length=200,help_text="文章标题")
    cate = models.ForeignKey(Cate,help_text="所属分类",on_delete=models.CASCADE)
    cover = models.ImageField(upload_to="article_img",help_text="文章封面")
    author = models.CharField(max_length=50,help_text="文章作者",blank=True,null=True)
    description = models.CharField(max_length=500,help_text="文章简介",blank=True,null=True)
    content = models.TextField()
    label = models.CharField(max_length=100,blank=True,null=True,help_text="文章标签")
    status = models.BooleanField(default=0,help_text="是否审核，0：未审核，1：已审核")
    display_mode = models.IntegerField(default=0,help_text="文章显示模式，0：标准模式，1：多图模式")
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    area = models.ForeignKey(Area,blank=True,null=True,on_delete=models.SET_NULL)
    famous = models.ForeignKey(Famous,blank=True,null=True,on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "图片文章"
        ordering = ['-update_time']

        permissions = (
            ("add_img_article","添加图片文章"),
            ("modify_img_article","修改图片文章"),
            ("delete_img_article","删除图片文章"),
            ("confirm_img_article","审核图片文章")
            )

class Images(models.Model):
    article = models.ForeignKey(ImgArticle,help_text="所属文章",on_delete=models.CASCADE)
    img = models.ImageField(upload_to="article_img")
    title = models.CharField(max_length=200,blank=True,null=True,help_text="图片标题")
    description = models.CharField(max_length=500,null=True,blank=True,help_text="图片简介")



class MediaArticle(models.Model):
    title = models.CharField(max_length=200,help_text="文章标题")
    cate = models.ForeignKey(Cate,help_text="所属分类",on_delete=models.CASCADE)
    cover = models.ImageField(upload_to="article_img",help_text="文章封面")
    author = models.CharField(max_length=50,help_text="文章作者",blank=True,null=True)
    media = models.FileField(upload_to="article_media")
    description = models.CharField(max_length=500,help_text="文章简介",blank=True,null=True)
    label = models.CharField(max_length=100,blank=True,null=True,help_text="文章标签")
    status = models.BooleanField(default=0,help_text="是否审核，0：未审核，1：已审核")
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "影视文章"
        ordering = ['-update_time']

        permissions = (
            ("add_media_article","添加视频文章"),
            ("modify_media_article","修改视频文章"),
            ("delete_media_article","删除视频文章"),
            ("confirm_media_article","审核视频文章")
            )

backend/templates/backend/add_area.html
{% extends 'backend/base.html' %}
{% block title %}添加地区{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<div class="layui-row">
<div class="layui-col-md8 layui-col-md-offset2">
<form class="layui-form" style="margin-top: 30px;" target="_parent" method="POST">
{% csrf_token %}
  <div class="layui-form-item">
  	<label class="layui-form-label">地区名称</label>
  	<div class="layui-input-block">
  		<input type="text" name="name" class="layui-input" lay-verify="required" value="" />
  	</div>
  </div>

  <input type="hidden" name="city_id" value="{{city.id}}">


  <div class="layui-form-item">
  	<div class="layui-input-block">
  		<button class="layui-btn" lay-submit>确定</button>
  	</div>
  </div>
</form>
</div>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
	$(document).ready(function(){
		layui.use('form',function(){
			var form = layui.form;
			form.render()
		})
	})
</script>
{% endblock %}

backend/templates/backend/add_carousel_item.html
{% extends 'backend/base.html' %}
{% block title %}添加轮播图片{% endblock %}
{% block header %}
{% endblock %}

{% block content %}
<form class="layui-form" method="POST" style="margin-top: 30px;" target="_parent">
{% csrf_token %}

  <input type="hidden" name="item_id" value="{{carousel_item.id}}">
  <input type="hidden" name="carousel_id" value="{{carousel.id}}">

  <div class="layui-form-item">
    <label class="layui-form-label">标题：</label>
    <div class="layui-input-block">
      <input type="text" name="title" lay-verify="required" class="layui-input" value="{{carousel_item.title}}" style="width: 600px;" />
    </div>
  </div>

  <div class="layui-form-item">
    <label class="layui-form-label">指向链接：</label>
    <div class="layui-input-block">
      <input type="text" name="url" lay-verify="required" class="layui-input" style="width: 600px;" value="{{carousel_item.url}}" />
    </div>
  </div>

  <div class="layui-form-item layui-form-text">
    <label class="layui-form-label">简介：</label>
    <div class="layui-input-block">
      <textarea class="layui-textarea" style="width: 600px;" name="desc">{{carousel_item.desc}}</textarea>
    </div>
  </div>

  <div class="layui-form-item">
    <label class="layui-form-label">轮播图片：</label>
    <div class="layui-input-block">
      <img src="/site_media/{{carousel_item.img}}" id="img" style="width: 200px;height: 200px;{% if not carousel_item %}opacity: 0;{% endif %}" /><a href="javascript:;" id="upload_img">上传图片</a>
      <input type="hidden" name="img_src" id="img_src" />
    </div>
  </div>


  <div class="layui-form-item">
    <div class="layui-input-block">
      <button class="layui-btn" lay-submit>提交</button>
      <button type="reset" class="layui-btn layui-btn-primary">重置</button>
    </div>
  </div>
</form>
{% endblock %}

{% block script %}
<script type="text/javascript">
$(document).ready(function(){
	layui.use("form",function(){
		var form = layui.form;
		form.render();
	})


   layui.use('upload',function(){
    var upload = layui.upload;

    var uploadInst = upload.render({
      elem:"#upload_img",
      auto:false,
      accept:"images",
      choose:function(obj){
        obj.preview(function(index,file,result){
             $("#img").attr("src",result).css("opacity",1)
             $("#img_src").val(result)
        })
      },
      done:function(res,index,upload){
          alert(res.msg);
          window.location.reload();
      },
      error:function(error){
        console.log(error)
      }
    })
  })
})
</script>
{% endblock %}

backend/templates/backend/add_cate.html
{% extends 'backend/base.html' %}
{% block title %}添加分类{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<div class="layui-row">
<div class="layui-col-md8 layui-col-md-offset2">
<form class="layui-form" style="margin-top: 30px;" target="_parent" method="POST">
{% csrf_token %}
  <div class="layui-form-item">
  	<label class="layui-form-label">分类名称</label>
  	<div class="layui-input-block">
  		<input type="text" name="name" class="layui-input" lay-verify="required" value="{{now_cate.name}}" />
  	</div>
  </div>

  <div class="layui-form-item">
  	<label class="layui-form-label">简介</label>
  	<div class="layui-input-block">
  		<textarea name="short_description" class="layui-textarea">{{now_cate.description}}</textarea>
  	</div>
  </div>
  

  <div class="layui-form-item">
  	<label class="layui-form-label">上级分类</label>
  	<div class="layui-input-block">
  		<select name="parent" id="parent">
  		    <option value="">--------</option>
  			{% for cate in cates %}
  			<option value="{{cate.id}}">{{cate.name}}</option>
  			{% endfor %}
  		</select>
  	</div>
  </div>

  <div class="layui-form-item">
  	<div class="layui-input-block">
  		<button class="layui-btn" lay-submit>确定</button>
  	</div>
  </div>
</form>
</div>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
	$(document).ready(function(){
		layui.use('form',function(){
			var form = layui.form;
			form.render()
		})

		{% if now_cate %}
		$("#parent").children("option[value={{now_cate.parent.id}}]").attr("selected","selected")
		{% endif %}
	})
</script>
{% endblock %}

backend/templates/backend/auth_group.html
{% extends 'backend/setting.html' %}
{% block title %}职位管理{% endblock %}
{% block right %}
<div class="layui-row">
	<div class="layui-col-md1 layui-col-md-offset10">
		<a href="javascript:;" class="layui-btn" id="add_group">添加职位</a>
	</div>
</div>

<table class="layui-table">
  <optgroup>
  </optgroup>
  <thead>
    <tr>
      <th>序号</th>
      <th>职位名称</th>
      <th>操作</th>
    </tr>
  </thead>

  <tbody>
    {% for group in groups %}
    <tr>
    <td>{{forloop.counter}}</td>
    <td>{{group.name}}</td>
    <td><a href="javascript:;" style="margin-left: 20px;" class="modify_permission" data="{{group.name}}">修改权限</a><a href="javascript:;" class="delete_group" data={{group.id}} style="margin-left: 20px;">删除</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
<div class="layui-row"> 
<div class="layui-col-md12" style="text-align: center;"> 
    <div class="pagination">  
        <span class="page-links">  
            {% if page_obj.has_previous %}  
                <a class="layui-btn layui-btn-primary" href="/backend/auth_group?page={{ page_obj.previous_page_number }}">上一页</a>  
            {% endif %}
            {% if i == page_obj.number %}
                <span style="padding: 25px;vertical-align: middle;">{{i}}</span>
            {% else %}
                <a class="layui-btn layui-btn-primary" href="/backend/auth_group?page={{i}}">{{i}}</a>
            {% endif %}
            {% if page_obj.has_next %}  
                <a class="layui-btn layui-btn-primary" href="/backend/auth_group?page={{ page_obj.next_page_number }}">下一页</a>  
            {% endif %}  
           <!-- <span class="page-current">  
                第{{ page_obj.number }}页 ，共{{ page_obj.paginator.num_pages }}页。  
            </span>  -->
        </span>  
    </div>  
</div>
</div>
{%endif%} 
{% endblock %}

{% block script %}
<script type="text/javascript">
$(document).ready(function(){
	$("#auth_group").addClass("layui-this")
	$("#setting").addClass("layui-this")

	layui.use('layer',function(){
			var layer = layui.layer;
			$("#add_group").click(function(){
			layer.open({
				type:2,
				content:"{% url 'backend:add_group' %}",
				title:'添加职位',
				area:['800px','400px']
			})
		})

      $(".modify_permission").click(function(){
        var data = $(this).attr("data")
      layer.open({
        type:2,
        content:"{% url 'backend:add_group' %}?group_name=" + data,
        title:'修改权限',
        area:['800px','400px']
      })
    })


    $(".delete_group").click(function(){
    var data = {group_id:$(this).attr("data")}
      layer.open({
        type:0,
        btn:["确认","取消"],
        yes:function(index,layero){
          $.ajax({
            type:"GET",
            url:"{% url 'backend:delete_group' %}",
            data:data,
            success:function(data){
              window.location.reload()
            }
          })
        },
        content:"确认进行操作",
        title:"删除职位",
        area:['400px','200px']
      })
    })


		})
})
</script>
{% endblock %}

backend/templates/backend/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'pc_front/layui/css/layui.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'backend/css/base.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'backend/css/pagination.css' %}">
	<script type="text/javascript" src="{% static 'pc_front/js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'pc_front/layui/layui.js' %}"></script>
    <script type="text/javascript" src="{% static 'pc_front/js/index.js' %}"></script>
    <script type="text/javascript">
    	$(document).ready(function(){
    		layui.use('element',function(){
    			var element = layui.element;
    		})
    	})
    </script>
</head>
<body>
<div class="layui-fluid">
{% block header %}
<div class="layui-row header" style="margin-top: 0">
  <div class="layui-col-md1 layui-col-md-offset1">
  	<a href="#" class="title">行走广西管理后台</a>
  </div>
  
  <div class="layui-col-md8">
  <ul class="layui-nav head-nav">
    <li class="layui-nav-item"><a href="{% url 'backend:index' %}">网站基本设置</a></li>
  	<li class="layui-nav-item" id="cate_setting"><a href="{% url 'backend:cate_setting' %}">分类设置</a></li>
  	<li class="layui-nav-item" id="article"><a href="{% url 'backend:article' %}">文章发布</a></li>
  	<li class="layui-nav-item"><a href="#">用户管理</a></li>
    <li class="layui-nav-item" id="city_setting"><a href="{% url 'backend:city_setting' %}">城市地区设置</a></li>
    <li class="layui-nav-item" id="topic_setting"><a href="{% url 'backend:topic_setting' %}">专题设置</a></li>
    <li class="layui-nav-item" id="operation_log"><a href="{% url 'backend:operation_log' %}">操作日志查询</a></li>
    {% if request.user.is_superuser %}
  	<li class="layui-nav-item" id="setting"><a href="{% url 'backend:setting' %}">系统管理</a></li>
    {% endif %}
  </ul>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="layui-col-md2 side-nav">
	{% block left %}
	{% endblock %}
</div>

<div class="layui-col-md10">
	{% block right %}
	{% endblock %}
</div>
</div>

{% endblock %}
</body>
{% block script %}
{% endblock %}
</html>

backend/templates/backend/city_setting.html
{% extends 'backend/base.html' %}
{% load static %}
{% block title %}城市设置{% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'backend/css/cate_setting.css' %}">
<div class="layui-row">
	<div class="layui-col-md1 layui-col-md-offset9"><a class="layui-btn" href="javascript:;" id="add_city" >添加城市</a></div>
	<div class="layui-col-md1"><a href="javascript:;" class="layui-btn" id="delete_city">删除城市</a></div>
</div>

<div class="layui-row cate_list">
	<div class="layui-col-md1 layui-col-md-offset1">编号</div>
	<div class="layui-col-md1">城市名称</div>
	<div class="layui-col-md6">区域</div>
	<div class="layui-col-md3">操作</div>
</div>

{% for c in city %}
<div class="layui-row cate_list">
	<div class="layui-col-md1 layui-col-md-offset1">{{forloop.counter}}</div>
	<div class="layui-col-md1">{{c.name}}</div>
	<div class="layui-col-md6">{% for area in c.area_set.all %}{{area.name}}，{% endfor %}</div>
	<div class="layui-col-md3">
	<a href="javascript:;" class="layui-btn add_area" data="{{c.id}}">添加地区</a><a href="javascript:;" class="layui-btn delete_area" data="{{c.id}}">删除地区</a><a href="javascript:;" class="layui-btn layui-btn-primary modify_city" data="{{c.id}}">修改</a>
	</div>
</div>
{% endfor %}

{% endblock %}

{% block script %}
<script type="text/javascript">
	$(document).ready(function(){
		$("#city_setting").addClass("layui-this")

		layui.use('layer',function(){
			var layer = layui.layer;
			$("#add_city").click(function(){
			layer.open({
				type:2,
				content:"{% url 'backend:add_city' %}",
				title:'添加/修改城市',
				area:['800px','500px']
			})
		})

			$(".modify_city").click(function(){
				var id = $(this).attr("data");
			layer.open({
				type:2,
				content:"/backend/add_city/?city_id="+id,
				title:'添加/修改城市',
				area:['800px','500px']
			})
		})

			$(".add_area").click(function(){
				var id = $(this).attr("data")
				layer.open({
				type:2,
				content:"/backend/add_area/?city_id="+id,
				title:'添加地区',
				area:['800px','200px']
			})
			})

			$(".delete_area").click(function(){
				var id = $(this).attr("data")
				layer.open({
				type:2,
				content:"/backend/delete_area/?city_id="+id,
				title:'删除地区',
				area:['800px','400px']
			})
			})

			$("#delete_city").click(function(){
				layer.open({
				type:2,
				content:"/backend/delete_city/",
				title:'删除城市',
				area:['800px','400px']
			})
			})
		})
	})
</script>
{% endblock %}

backend/templates/backend/delete_area.html
{% extends 'backend/base.html' %}
{% block title %}选择删除的地区{% endblock %}
{% block header %}
{% endblock %}

{% block content %}
<form class="layui-form" method="POST" style="margin-top: 30px;" target="_parent">
{% csrf_token %}

  <div class="layui-form-item" style="width: 600px;">
    <label class="layui-form-label">选择删除的地区：</label>
    <div class="layui-input-block">
      <select name="area_id" lay-verify="required" lay-filter="item">
        <option value=""></option>
        {% for area in city.area_set.all %}
        <option value="{{area.id}}">{{area.name}}</option>
        {% endfor %}
      </select>
    </div>
  </div>

  <div class="layui-form-item">
    <div class="layui-input-block">
      <button class="layui-btn" lay-submit>确定</button>
    </div>
  </div>

</form>
{% endblock %}

{% block script %}
<script type="text/javascript">
$(document).ready(function(){
	layui.use("form",function(){
		var form = layui.form;

		form.render();
	})
})
</script>
{% endblock %}

backend/templates/backend/delete_topic_article.html
{% extends 'backend/base.html' %}
{% block title %}删除专题文章{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<div class="layui-row">
<div class="layui-col-md8 layui-col-md-offset2">
<form class="layui-form" style="margin-top: 30px;" target="_parent" method="POST">
{% csrf_token %}
  <div class="layui-form-item" style="width: 600px;">
    <label class="layui-form-label">要移除专题的文章：</label>
    <div class="layui-input-block">
      <select name="article_id" lay-verify="required" lay-filter="item">
        <option value=""></option>
        {% for a in article %}
        <option value="{{a.id}}">{{a.title}}</option>
        {% endfor %}
      </select>
    </div>
  </div>

  <input type="hidden" name="topic_id" value="{{topic.id}}">


  <div class="layui-form-item">
  	<div class="layui-input-block">
  		<button class="layui-btn" lay-submit>确定</button>
  	</div>
  </div>
</form>
</div>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
	$(document).ready(function(){
		layui.use('form',function(){
			var form = layui.form;
			form.render()
		})
	})
</script>
{% endblock %}

backend/templates/backend/error.html
{% extends 'backend/base.html' %}
{% block title %}错误{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
{{error_message}}
{% endblock %}

backend/templates/backend/modify_article_img.html
{% extends 'backend/base.html' %}
{% block title %}选择修改的图片{% endblock %}
{% block header %}
{% endblock %}

{% block content %}
<form class="layui-form" method="GET" style="margin-top: 30px;" target="_parent">
{% csrf_token %}

  <div class="layui-form-item" style="width: 600px;">
    <label class="layui-form-label">选择修改的图片：</label>
    <div class="layui-input-block">
      <select name="cate" lay-verify="required" lay-filter="item">
        <option value=""></option>
        {% for item in imgs %}
        <option value="{{item.id}}">{{item.title}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
</form>
{% endblock %}

{% block script %}
<script type="text/javascript">
$(document).ready(function(){
	layui.use("form",function(){
		var form = layui.form;

    form.on("select(item)",function(data){
      value = data.value;
      window.location.href = "{% url 'backend:add_article_img' %}?article_id={{article.id}}&img_id=" + value
    })

		form.render();
	})
})
</script>
{% endblock %}